### PR TITLE
Feature/44 - implement page 3 of the form 

### PR DESCRIPTION
**Pull request by Kaspr-whtev**
image

### CODE REVIEW

**Review by mustafaMari — COMMENTED** [review]
Are we sure we want to go with a slider for the Time Between Events, do you not think an input would be better? 
image
can't we do something similar, instead of choosing time we would have hours on the left side and minutes on the right side, then you would be converted to minutes before sending the request to the backend

**Comment by Kaspr-whtev** [comment]
> 

well the problem is with days, in the begging we wanted to use a picker like this, however we would need it to be in the format days:hours:minutes, which is difficult to do in antd

**Comment by mustafaMari** [comment]
In that case, I would make it Days: Hours no need for minutes, If I want to specify the time between events I most definitely going to say in 6 days, not 6 days 6 hours, and 6 minutes

**Comment by Kaspr-whtev** [comment]
the problem is with combining "date" elements with "time" elements so hour:minute is no problem, but as soon as you try to add day to that it stops playing nice. Believe me, I'd prefer an alternative solution  to the slider, but implementation of such a component would take way to long.

And I do agree that days are the most important out of the 3, so we either implement it like it is now or we leave just days, which imo is to restrictive.

**Comment by mustafaMari** [comment]
got it, it is not essential

**Review by mustafaMari — APPROVED** [review]

**Pull request merged**
